module.exports = {
  SET_START_TEXT_SCENE: 'SET_START_TEXT_SCENE',
  SET_FINISH_TEXT_SCENE: 'SET_FINISH_TEXT_SCENE',
  EDIT_QUESTIONS_SCENE: 'EDIT_QUESTIONS_SCENE',
  CREATE_QUESTION_SCENE: 'CREATE_QUESTION_SCENE',
  USER_FORM_SCENE: 'USER_FORM_SCENE',
};